tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "cmake"
brew "deno"
brew "fish"
brew "jq"
brew "mysql", restart_service: true
brew "ncurses"
brew "neovim"
brew "redis", restart_service: true
brew "selecta"
brew "stow"
brew "tmux"
brew "vim"
cask "font-fira-code"
cask "font-source-code-pro"
