# Colors (Argonaut)

[colors.bright]
black = '#444444'
blue = '#0092ff'
cyan = '#67fff0'
green = '#abe15b'
magenta = '#9a5feb'
red = '#ff2740'
white = '#ffffff'
yellow = '#ffd242'

[colors.cursor]
cursor = '#ff0018'
text = '#ff0018'

[colors.normal]
black = '#232323'
blue = '#008df8'
cyan = '#00d8eb'
green = '#8ce10b'
magenta = '#6d43a6'
red = '#ff000f'
white = '#ffffff'
yellow = '#ffb900'

[colors.primary]
background = '#0e1019'
foreground = '#fffaf4'

[colors.selection]
background = '#002a3b'
text = '#ffffff'
