# Colors (Atom)

[colors.bright]
black = '#000000'
blue = '#96cbfe'
cyan = '#85befd'
green = '#94fa36'
magenta = '#b9b6fc'
red = '#fd5ff1'
white = '#e0e0e0'
yellow = '#f5ffa8'

[colors.cursor]
cursor = '#d0d0d0'
text = '#151515'

[colors.normal]
black = '#000000'
blue = '#85befd'
cyan = '#85befd'
green = '#87c38a'
magenta = '#b9b6fc'
red = '#fd5ff1'
white = '#e0e0e0'
yellow = '#ffd7b1'

[colors.primary]
background = '#161719'
foreground = '#c5c8c6'

[colors.selection]
background = '#444444'
text = '#c5c8c6'
