# Colors (CGA)

[colors.bright]
black = '#555555'
blue = '#5555ff'
cyan = '#55ffff'
green = '#55ff55'
magenta = '#ff55ff'
red = '#ff5555'
white = '#ffffff'
yellow = '#ffff55'

[colors.cursor]
cursor = '#b8b8b8'
text = '#ffffff'

[colors.normal]
black = '#000000'
blue = '#0000aa'
cyan = '#00aaaa'
green = '#00aa00'
magenta = '#aa00aa'
red = '#aa0000'
white = '#aaaaaa'
yellow = '#aa5500'

[colors.primary]
background = '#000000'
foreground = '#aaaaaa'

[colors.selection]
background = '#c1deff'
text = '#000000'
