# Colors (detuned)

[colors.bright]
black = '#686868'
blue = '#55bbf9'
cyan = '#7fd4fb'
green = '#c5e280'
magenta = '#b9a0f9'
red = '#ea86ac'
white = '#ffffff'
yellow = '#fdf38f'

[colors.cursor]
cursor = '#c7c7c7'
text = '#ffffff'

[colors.normal]
black = '#171717'
blue = '#4192d3'
cyan = '#6cb4d5'
green = '#b3e153'
magenta = '#8f3ef6'
red = '#ea5386'
white = '#c7c7c7'
yellow = '#e4da81'

[colors.primary]
background = '#000000'
foreground = '#c7c7c7'

[colors.selection]
background = '#c7ddfc'
text = '#000000'
