# Colors (Dracula+)

[colors.bright]
black = '#545454'
blue = '#d6acff'
cyan = '#a4ffff'
green = '#69ff94'
magenta = '#ff92df'
red = '#ff6e6e'
white = '#f8f8f2'
yellow = '#ffcb6b'

[colors.cursor]
cursor = '#eceff4'
text = '#282828'

[colors.normal]
black = '#21222c'
blue = '#82aaff'
cyan = '#8be9fd'
green = '#50fa7b'
magenta = '#c792ea'
red = '#ff5555'
white = '#f8f8f2'
yellow = '#ffcb6b'

[colors.primary]
background = '#212121'
foreground = '#f8f8f2'

[colors.selection]
background = '#f8f8f2'
text = '#545454'
