# Colors (Material)

[colors.bright]
black = '#424242'
blue = '#54a4f3'
cyan = '#26bbd1'
green = '#7aba3a'
magenta = '#aa4dbc'
red = '#e83b3f'
white = '#d9d9d9'
yellow = '#ffea2e'

[colors.cursor]
cursor = '#16afca'
text = '#2e2e2d'

[colors.normal]
black = '#212121'
blue = '#134eb2'
cyan = '#0e717c'
green = '#457b24'
magenta = '#560088'
red = '#b7141f'
white = '#efefef'
yellow = '#f6981e'

[colors.primary]
background = '#eaeaea'
foreground = '#232322'

[colors.selection]
background = '#c2c2c2'
text = '#4e4e4e'
