# Colors (Subliminal)

[colors.bright]
black = '#7f7f7f'
blue = '#6699cc'
cyan = '#5fb3b3'
green = '#a9cfa4'
magenta = '#f1a5ab'
red = '#e15a60'
white = '#d4d4d4'
yellow = '#ffe2a9'

[colors.cursor]
cursor = '#c7c7c7'
text = '#ffffff'

[colors.normal]
black = '#7f7f7f'
blue = '#6699cc'
cyan = '#5fb3b3'
green = '#a9cfa4'
magenta = '#f1a5ab'
red = '#e15a60'
white = '#d4d4d4'
yellow = '#ffe2a9'

[colors.primary]
background = '#282c35'
foreground = '#d4d4d4'

[colors.selection]
background = '#484e5b'
text = '#ffffff'
