default_host_triple = "x86_64-apple-darwin"
default_toolchain = "stable-x86_64-apple-darwin"
telemetry = false
version = "12"

[overrides]
"/Users/voidedgin/code/sketches/rust/lol" = "nightly-x86_64-apple-darwin"
