default_host_triple = "x86_64-apple-darwin"
default_toolchain = "stable-x86_64-apple-darwin"
profile = "default"
version = "12"

[overrides]
"/Users/voidedgin/Projects/wishlist/server" = "nightly-x86_64-apple-darwin"
"/Users/voidedgin/code/sketches/rust/lol" = "nightly-x86_64-apple-darwin"
